### ISSUE TITLE
Use free domain for website

### ISSUE THREAD

**Issue by impredicative** [html-extract/html-extract.github.io#1]
For added safety, please consider using a free domain, e.g. github.io, for hosting this site. The site must remain available online for a long time without being dependent on one person or on a paid domain name. Thank you.

**Comment by thomastrapp** [comment]
That's definitely a good point.

I am pretty sure that hext.thomastrapp.com will be up for a long time, but Github's CDN is reason enough to switch. Currently hext.thomastrapp.com is hosted in Frankfurt Germany, and I have no idea how good or bad the connection is outside of Europe. And, as far as I am aware, there are no Germans using hext :)

The "Try Hext in Your Browser"-section will need its own machine unfortunately, but that is free software as well (`hext-on-websockets`), if I ever get hit by the proverbial "bus factor", and somebody actually needs it.

I'll have to do some clean-up, but I think I'll be able to switch to github.io in the coming weeks.

Thank you for caring!

**Comment by impredicative** [comment]
Out of curiosity, is there any way for "Try Hext in Your Browser" to run on the client side in the browser? I don't need it. I am just asking as a potential alternative to hext-on-websockets.

Fwiw, the connection is currently fine here in the US :)  I couldn't have guessed that it was not hosted domestically.

**Comment by thomastrapp** [comment]
I haven't tried it out myself (yet), but if I understood correctly, [Brandon Robertz](https://github.com/brandonrobertz) actually managed to compile hext for JavaScript to run in browsers:
https://github.com/brandonrobertz/hext-emscripten

I am told that WASM improved a lot over the years (in performance and features), so this is very nice to see.

> Fwiw, the connection is currently fine here in the US :) I couldn't have guessed that it was not hosted domestically.

Great to hear. It is running on a 5$ droplet from digitalocean.com, but I guess there's not much traffic.

**Comment by impredicative** [comment]
Maybe @brandonrobertz can think of relocating his repo into the new html-extract organization that is managed by @thomastrapp and managing it there, assuming no one is opposed to this idea. This is independent of this Issue.

**Comment by thomastrapp** [comment]
The more, the merrier!
I'll get in contact with @brandonrobertz once I've moved my own repos to the org.

**Comment by impredicative** [comment]
As an alternative, it should be possible to host hext in a serverless setting which has no charge for maybe a million requests a month, with this being sufficient for the website. It will still need a credit card to set up the serverless project. I have used Google Cloud Functions with Python in this manner, but I think Javascript is supported too. This is via REST.

This would cost you $0 per month, assuming (1) you don't already use Cloud Functions (2) an un-expired credit card is always supplied (3) the number of requests stay below the generous free monthly limit. Even so, of course it's not as optimal as it running on the client directly.

I am not asking for this; I am just stating my thoughts.

**Comment by thomastrapp** [comment]
Good point, maybe that is something to look into in the future.

**Comment by thomastrapp** [comment]
Hext's website is now also available at https://html-extract.github.io/

Thank you for your input!

**Comment by impredicative** [comment]
Great. Please of course note both URLs in the readme whenever you add one. Thanks.
